using Microsoft.CodeAnalysis;
using MVVMGenerators.Helpers;
using System.Collections.Generic;
using System.Collections.Immutable;
using MVVMGenerators.Helpers.Descriptions;

namespace MVVMGenerators.Generators.Ids;

public partial class IdGenerator
{
    // ReSharper disable once InconsistentNaming
    private static readonly string EditorBrowsableAttribute = $"[{Classes.EditorBrowsableAttribute}({Classes.EditorBrowsableState}.Never)]";
    
    private static void GenerateCode(
        SourceProductionContext context, 
        ImmutableArray<HashSet<string>> idsList)
    {
        var code = new CodeWriter();

        code.AppendLine("// <auto-generated>")
            .AppendLine("namespace Aspid.MVVM.Generated")
            .BeginBlock()
            .AppendLine(EditorBrowsableAttribute)
            .AppendLine("internal static class Ids")
            .BeginBlock();
        
        var allIds = new HashSet<string>();
        
        foreach (var ids in idsList)
        {
            foreach (var id in ids)
            {
                allIds.Add(id);
            }
        }

        foreach (var id in allIds)
        {
            code.AppendLine(EditorBrowsableAttribute);
            code.AppendLine($"public const string {id} = \"{id}\";");
        }

        code.EndBlock()
            .EndBlock();

        context.AddSource("Ids", code.GetSourceText());
    }
}