using System;

namespace MVVMGenerators.Helpers.Extensions;

public static class CodeWriteClassExtension
{
    public static CodeWriter AppendClass(this CodeWriter code, 
        string namespaceName, DeclarationText declarationText, Action? body, params string[] baseTypes)
    {
        var hasNamespace = !string.IsNullOrEmpty(namespaceName);
        var hasBaseTapes = baseTypes is { Length: > 0 };
        
        code.AppendLine("// <auto-generated>")
            .AppendChildIf(hasNamespace, () => code
                .AppendLine($"namespace {namespaceName}")
                .BeginBlock())
            .AppendLineIf(!hasBaseTapes, $"{declarationText}")
            .AppendLineIf(hasBaseTapes, $"{declarationText} : {string.Join(",", baseTypes)}")
            .BeginBlock();

        body?.Invoke();
        code.EndBlock()
            .EndBlockIf(hasNamespace);

        return code;
    }
}