using System;

namespace MVVMGenerators.Helpers.Extensions;

public static class CodeWriteClassExtension
{
    public static CodeWriter AppendClass(this CodeWriter code, 
        string namespaceName, DeclarationText declarationText, Action? body, params string[]? baseTypes)
    {
        var hasNamespace = !string.IsNullOrEmpty(namespaceName);

        var baseTypesText = "";
        if (baseTypes is { Length: > 0 }) baseTypesText = $" : {string.Join(",", baseTypes!)}";
        
        code.AppendLine("// <auto-generated>")
            .AppendChildIf(hasNamespace, () => code
                .AppendLine($"namespace {namespaceName}")
                .BeginBlock())
            .AppendLine($"{declarationText}{baseTypesText}")
            .BeginBlock();

        body?.Invoke();
        code.EndBlock()
            .EndBlockIf(hasNamespace);

        return code;
    }
}